foodee/config/routes.rb
Foodee::Application.routes.draw do

  resources :restaurants, :dishes

  root :to => 'home#index'

end

foodee/app/models/dish.rb
# == Schema Information
#
# Table name: dishes
#
#  id    :integer          not null, primary key
#  name  :string(255)
#  cost  :decimal(, )
#  photo :string(255)
#

class Dish < ActiveRecord::Base
  belongs_to :restaurant
  validates :name, :presence => true
  validates :cost, :numericality => { :greater_than => 10 }
  validates :photo, :presence => true
end

foodee/app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id      :integer          not null, primary key
#  name    :string(255)
#  cuisine :string(255)
#  address :text
#

class Restaurant < ActiveRecord::Base
  has_many :dishes
  validates :name, :length => { :minimum => 4 }
  validates :cuisine, :presence => true
  validates :address, :presence => true
end

foodee/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

foodee/app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def index
    @dishes = Dish.all
    # creates an array of all the dishes in a restaurant
  end
  def show
    dish_id = params[:id]
    @dish = Dish.find(dish_id)
  end
  def new
    @dish = Dish.new
  end
  def edit
    @dish = Dish.find(params[:id])
  end
  def create
    @dish = Dish.new(params[:dish])
    if @dish.save
      redirect_to dishes_path
      # redirect to dishes page if saved properly
    else
      render :new
      # stay on the form page
    end
  end
  def update
    @dish = Dish.find(params[:id])
    if @dish.update_attributes(params[:dish])
      redirect_to @dish
    else
      render :edit
    end
  end
  def destroy
    dish = Dish.find(params[:id])
    dish.delete
    redirect_to dishes_path
  end
end

foodee/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

foodee/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
    # creates an array of all the dishes in a restaurant
  end
  def show
    restaurant_id = params[:id]
    @restaurant = Restaurant.find(restaurant_id)
  end
  def new
    @restaurant = Restaurant.new
  end
  def edit
    @restaurant = Restaurant.find(params[:id])
  end
  def create
     @restaurant = Restaurant.new(params[:restaurant])

    if @restaurant.save
      redirect_to restaurants_path
      # redirect to dishes page if saved properly
    else
      render :new
      # stay on the form page
    end
  end
  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update_attributes(params[:restaurant])
      redirect_to @restaurant
    else
      render :edit
    end
  end
  def destroy
    restaurant = Restaurant.find(params[:id])
    restaurant.delete
    redirect_to restaurants_path
  end
end

foodee/app/helpers/application_helper.rb
module ApplicationHelper
end

foodee/app/views/dishes/_form.html.erb
<%= render :partial => 'shared/errors', :locals => {:object => @dish} %>

<!-- will change object to @restaurant and run partial error -->

<%= form_for @dish do |f| %>
<div class="forms">

  <div class="field">
    <%= f.label :restaurant_id %>
    <%= f.select :restaurant_id, Restaurant.all.map{|r| [r.name, r.id]} %>
  </div>


  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :cost %>
    <%= f.number_field :cost %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <%= f.text_field :photo %>
  </div>

  <%= f.submit %>
</div>
<% end %>

foodee/app/views/dishes/edit.html.erb
<h1>Edit Dish</h1>
<%= render 'form' %>

foodee/app/views/dishes/index.html.erb
<h1>Dishes</h1>

<div class="button">
  <%= link_to 'Add A Dish', new_dish_path %>
</div>

<div class ="clear"></div>
<br />

<div class = "list">
  <ul>
    <% @dishes.each do |dish| %>
      <li><%= link_to dish.name, dish %></li>
    <% end %>
  </ul>
</div>

foodee/app/views/dishes/new.html.erb
<h1>New Dish</h1>
<%= render 'form' %>

foodee/app/views/dishes/show.html.erb
<div class ="item">

  <h1><%= link_to @dish.name, edit_dish_path(@dish) %></h1>
  <div class ="cost">
    <p><%= number_to_currency @dish.cost %></p>
  </div>
  <%= image_tag @dish.photo %>

  <div class = "button"><%= link_to "delete", dish_path(@dish), :method => :delete, :confirm => "Are you sure?" %></div>
  <div class = "clear"></div>

</div>

foodee/app/views/home/index.html.erb
<div id="main">

<div id="intro">
  <h1>Welcome to the Foodie App</h1>
</div>

<div id="controls">
  <div class="button">
    <%= link_to "View the Foodie Restaurants", restaurants_path %><br>
  </div> 

  <div class="button">
    <%= link_to "View the Foodie Restaurant Dishes", dishes_path %><br>
  </div>
</div><!-- end controls -->

  <div class = "clear"></div>

  <div id = "names">
    <h2 id="create" class="heroes">Created by: </h2>

    <h4 id="show1" class="heroes">Jasmine</h4>
    <h4 id="show2" class="heroes">Adrian</h4>
    <h4 id="show3" class="heroes">Larry</h4>
    <h4 id="show4" class="heroes">Derrick</h4>
  </div>

</div>

foodee/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodee</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script type="text/javascript" src="//use.typekit.net/wge4dni.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

</head>
<body>

<div class ="container">
  <header><%= link_to "Foodie App", root_path %> :: <%= link_to "Restaurants", restaurants_path %> :: <%= link_to "Dishes", dishes_path %>
<div class ="social">
  <ul>
    <li class="facebook"><a href="#"></a></li>
    <li class="twitter"><a href="#"></a></li>
    <li class="github"><a href="#"></a></li>
  </ul>
</div>

  </header>

<%= yield %>

</div>

</body>
</html>

foodee/app/views/restaurants/_form.html.erb
<%= render :partial => 'shared/errors', :locals => {:object => @restaurant} %>

<%= form_for @restaurant do |f| %>
<div class="forms">
	<div class='field'>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>
	<div class='field'>
		<%= f.label :cuisine %>
		<%= f.text_field :cuisine %>
	</div>
	<div class='field'>
		<%= f.label :address %>
		<%= f.text_field :address %>
	</div>
	<div class='field'>
		<% Dish.all.each do |dish| %>
			<%= check_box_tag 'restaurant[dish_ids][]', dish.id, @restaurant.dishes.include?(dish) %>
			<!-- each check box has its own id -->
			<span><%= dish.name %></span>
		<% end %>
	</div>
	<div class='field'>
		<%= f.submit %>
	</div>
</div>
<% end %>

foodee/app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render 'form' %>

foodee/app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<div class="button">
  <%= link_to 'Add A Restaurant', new_restaurant_path %>
</div>

<div class ="clear"></div>
<br />

<div class = "list">
  <ul>
  <% @restaurants.each do |restaurant| %>
  	<li>
  		<p><%= link_to restaurant.name, restaurant %></p>
  	</li>

  <% end %>
  </ul>
</div>

foodee/app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

foodee/app/views/restaurants/show.html.erb
<div class ="item">

  <h1><%= link_to @restaurant.name, edit_restaurant_path(@restaurant) %></h1>
  <div class="cuisine"><%= @restaurant.cuisine %> :: 
  <%= @restaurant.address %></div>

<div class = "button"><%= link_to "delete", restaurant_path(@restaurant), :method => :delete, :confirm => "Are you sure?" %>
</div>

  <div class = "clear"></div>

</div>

foodee/app/views/shared/_errors.html.erb
<ul class='errors'>
  <% object.errors.full_messages.each do |error| %>
  <!-- object applies to something with errors -->
  <li><%= error %></li>
  <% end %>
</ul>